Repository Nexters/Full-Stack-Android, pull requests merged in 2021-03, with the labels that each got.

#43 라벨링 메인 ( 피그마 3 )
  app/src/main/java/com/nexters/fullstack/ui/fragment/LabelSelectFragment.kt
  app/src/main/java/com/nexters/fullstack/ui/fragment/MyAlbumFragment.kt
  app/src/main/java/com/nexters/fullstack/util/AnimationUtils.kt
  app/src/main/res/anim/fade_in_animation.xml
  app/src/main/res/anim/fade_out_animation.xml
  app/src/main/res/layout/fragment_label_select.xml
  app/src/main/res/layout/selected_label_item.xml
  presentation/src/main/java/com/nexters/fullstack/viewmodel/LabelingViewModel.kt
Labels: UI, review need

#44 3_라벨 : 라벨 생성 UI
  app/src/main/java/com/nexters/fullstack/ui/fragment/MyAlbumFragment.kt
  app/src/main/res/layout/activity_create_label.xml
Labels: BUSINESS, UI, review need

#50 [ Feat ] 라벨링 메인 UI
  app/src/main/java/com/nexters/fullstack/binding/RecyclerBinding.kt
  app/src/main/java/com/nexters/fullstack/binding/ViewBinding.kt
  app/src/main/java/com/nexters/fullstack/ui/adapter/LocalImageAdapter.kt
  app/src/main/java/com/nexters/fullstack/ui/fragment/MyAlbumFragment.kt
  app/src/main/java/com/nexters/fullstack/ui/holder/LocalImageViewHolder.kt
  app/src/main/res/drawable/ic_ico_empty_screenshot.xml
  app/src/main/res/layout/fragment_myalbum.xml
  app/src/main/res/layout/recycler_album_item.xml
  presentation/src/main/java/com/nexters/fullstack/viewmodel/LabelingViewModel.kt
Labels: UI, done, review need

#51 Feat/#34 onboarding
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/onboarding1.json
  app/src/main/assets/onboarding2.json
  app/src/main/assets/onboarding3.json
  app/src/main/java/com/nexters/fullstack/Constants.kt
  app/src/main/java/com/nexters/fullstack/ui/activity/OnBoardingActivity.kt
  app/src/main/java/com/nexters/fullstack/ui/activity/SplashActivity.kt
  app/src/main/java/com/nexters/fullstack/ui/fragment/OnBoardingFragment.kt
  app/src/main/java/com/nexters/fullstack/util/PrefDataStoreManager.kt
  app/src/main/res/drawable/bg_indicator.xml
  app/src/main/res/drawable/indicator_default.xml
  app/src/main/res/drawable/indicator_focused.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  feature/build/intermediates/incremental/packageDebugResources/compile-file-map.properties
  feature/build/kotlin/compileDebugKotlin/build-history.bin
  feature/build/kotlin/compileDebugKotlin/last-build.bin
  presentation/src/main/java/com/nexters/fullstack/di/ViewModelModule.kt
  presentation/src/main/java/com/nexters/fullstack/viewmodel/OnBoardingViewModel.kt
Labels: UI, done, review need

#58 feat: 앱바 offset Listener
  app/src/main/java/com/nexters/fullstack/ui/fragment/MyAlbumFragment.kt
  app/src/main/java/com/nexters/fullstack/ui/widget/bottomsheet/recyclerview/GridLayoutRecyclerOnScrollListener.kt
  app/src/main/res/anim/slide_right.xml
  app/src/main/res/layout/fragment_myalbum.xml
  app/src/main/res/values/colors.xml
  feature/build/intermediates/incremental/packageDebugResources/merger.xml
  feature/build/kotlin/compileDebugKotlin/build-history.bin
  feature/build/kotlin/compileDebugKotlin/last-build.bin
Labels: UI, done
